(function(){
'use strict';
const $=id=>document.getElementById(id),q=new URLSearchParams(location.search),m=OperationsMissions[q.get('mission')]||OperationsMissions.m2,C=OperationsCore;
const key='maresp_operations_v2_'+(q.get('participant')||'local')+'_'+m.id+(q.get('preview')==='1'?'_preview':'');
let s=C.fresh(m.id),run=0,busy=false,viewKey="",activeContact='';try{const old=JSON.parse(localStorage.getItem(key));if(old?.version===2&&old.mission===m.id&&old.stage>=0&&old.stage<m.stages.length)s=old;}catch(e){}
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
function publish(){if(parent!==window)parent.postMessage({type:'maresp-mission-result',missionId:'itm2_live_'+m.id,result:C.packet(m,s)},location.origin);}
function save(){s.updatedAt=new Date().toISOString();try{localStorage.setItem(key,JSON.stringify(s));$('save-status').textContent='Guardado en este dispositivo';}catch(e){$('save-status').textContent='Storage unavailable — export your record';}}
function exportRecord(format='json'){const packet=C.packet(m,s);packet.participant=q.get('participant')||'local';let body=JSON.stringify(packet,null,2),type='application/json';if(format==='md'){body=['# '+m.title,'Status: '+s.completionStatus+' · Workflow: '+s.done.length+'/8','Participant: '+packet.participant,m.basis,'## Sources',...m.sourceNotes.map(x=>'- '+x),'## Student communications',...m.stages.flatMap(t=>['### '+t.title,'Recipient / record: '+t.delivery,...t.fields.map(f=>'**'+f.label+'**\n\n'+(s.answers[t.id]?.[f.id]||'[Not submitted]'))]),'## Decision trail',...s.log.map(x=>'- '+x.time+' · '+x.text),'## Operational communications',...s.messages.map(x=>'### '+x.stage+' · '+x.role+'\n\n'+x.content),'## Interpretation','Workflow completion checks required sources, required selections and minimum response completeness. It is not an automated language or competence grade. Drafts require instructor review.'].join('\n\n');type='text/markdown';}const a=el('a');a.href=URL.createObjectURL(new Blob([body],{type}));a.download=m.id+'-mission-record.'+format;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}

function feedback(){const done=s.done.includes(m.stages[s.stage].id);$('submit').disabled=done;$('outcome').textContent=done?m.stages[s.stage].consequence:'';$('continue').hidden=!done||s.stage===m.stages.length-1;$('finish').hidden=s.completionStatus!=='complete';$('progress-label').textContent=s.done.length+' / '+m.stages.length;$('progress-bar').style.width=(100*s.done.length/m.stages.length)+'%';$('trace').replaceChildren(...s.log.slice(-8).map(x=>el('p',x.text)));}
function richText(text){const box=el('div');for(const line of text.split('\n').filter(x=>x.trim())){const p=el('p');for(const [i,part] of line.split(/\*\*(.*?)\*\*/g).entries())p.append(i%2?el('strong',part):document.createTextNode(part));box.append(p);}return box;}
function chat(){const list=s.messages.filter(x=>x.stage===m.stages[s.stage].id&&x.mode==='simulation'&&x.contact===activeContact);$('ai-log').replaceChildren(...list.map(x=>{const n=el('div',undefined,'chat-message '+x.role);n.append(el('strong',x.role==='user'?'You → '+x.contact:x.contact),richText(x.content));return n;}));$('ai-log').scrollTop=$('ai-log').scrollHeight;}

function openSource(d){$('doc-title').textContent=d.title;$('doc-ref').textContent=d.ref;$('doc-body').textContent=d.body;s.read[d.id]=new Date().toISOString();save();$('documents').querySelectorAll('button').forEach(b=>{b.classList.toggle('selected',b.id==='doc-'+d.id);if(b.id==='doc-'+d.id){b.classList.add('read');b.lastChild.textContent='Consultado · volver a leer';}});}
function render(){const changed=viewKey!==s.createdAt+':'+s.stage;if(changed){viewKey=s.createdAt+':'+s.stage;run++;busy=false;$('ai-send').disabled=false;$('ai-status').textContent='Canal disponible. Contacta con el interlocutor de esta operación.';activeContact='';$('ai-input').value='';}const t=m.stages[s.stage];document.title=m.title+' · MAR-ESP';$('mission-no').textContent='MISSION '+m.number;$('mission-title').textContent=m.title;$('mission-subtitle').textContent={m2:'Coordinación de salida · MV Aurora',m3:'Investigación de un incidente · Rickmers Dubai',m4:'Inspección y seguimiento · MV Meridian'}[m.id];$('assignment').textContent=m.role+' · '+m.ship;$('mission-meta').textContent=m.duration+' · '+m.clock;const guide=OperationsGuide[m.id][s.stage];$('phase-title').textContent=guide[0];$('phase-time').textContent=t.time;$('phase-kind').textContent=m.kind;$('objective').textContent=guide[1];$('briefing').textContent='PASO '+(s.stage+1)+' DE 8 · Lee las instrucciones en español y redacta las comunicaciones en inglés.';$('action-guide').replaceChildren(...guide.slice(2,5).map(x=>el('li',x)));$('checklist').replaceChildren(...guide[5].map(x=>el('li',x)));$('delivery').textContent='Entrega de este paso: '+t.delivery;$('ai-role').textContent=t.aiRole;$('ai-purpose').textContent='Comunicación operativa: solicita información, transmite órdenes o comunica incidencias.';$('sources').replaceChildren(el('p',m.basis),...m.sourceNotes.map(x=>el('p',x)));$('errors').replaceChildren();
$('steps').replaceChildren(...m.stages.map((st,i)=>{const b=el('button',s.done.includes(st.id)?'✓':String(i+1));b.title=OperationsGuide[m.id][i][0];b.setAttribute('aria-label','Paso '+(i+1)+': '+OperationsGuide[m.id][i][0]);b.setAttribute('aria-current',i===s.stage?'step':'false');b.disabled=i>s.done.length;b.className=i===s.stage?'active':'';b.onclick=()=>{s.stage=i;save();render();};return b;}));
$('documents').replaceChildren(...C.available(m,s).filter(d=>t.docs.includes(d.id)).map(d=>{const b=el('button',undefined,'source-button'+(s.read[d.id]?' read':''));b.append(el('b',d.title),el('span',s.read[d.id]?'Consultado · volver a leer':'Abrir documento','doc-state'));b.id='doc-'+d.id;b.onclick=()=>openSource(d);return b;}));
$('doc-title').textContent='Selecciona un documento';$('doc-ref').textContent='';$('doc-body').textContent='Los documentos se leen aquí, junto a tu zona de trabajo.';document.body.dataset.mission=m.id;$('visual').replaceChildren();
$('fields').replaceChildren(...t.fields.map(f=>{const wrap=el('div',undefined,'field'),label=el('label',OperationsGuide.fieldLabels[f.id]||f.label);label.htmlFor='field-'+f.id;let input;if(f.type==='text'){input=el('textarea');input.rows=f.min>500?9:4;input.placeholder=f.id==='reflection'?'Cita una expresión de tu texto y explica qué cambiaste y qué efecto tiene.':t.fields.filter(x=>x.type==='text')[0].id===f.id?guide[6]+' (continúa con tu propio mensaje)':'Redacta aquí tu respuesta en inglés, usando los datos de las fuentes.';}else{input=el('select');input.append(new Option('Selecciona según las fuentes',''));const opts=f.options||[{value:'port-forward',label:'Port forward'},{value:'starboard-forward',label:'Starboard forward'},{value:'port-aft',label:'Port aft'},{value:'starboard-aft',label:'Starboard aft'}];opts.forEach(o=>input.append(new Option(o.label,o.value)));}input.id='field-'+f.id;input.value=s.answers[t.id]?.[f.id]||'';const count=el('small',f.type==='text'?input.value.trim().split(/\s+/).filter(Boolean).length+' words':'');input.addEventListener('input',()=>{const was=s.done.includes(t.id);C.edit(m,s,f.id,input.value);save();count.textContent=f.type==='text'?input.value.trim().split(/\s+/).filter(Boolean).length+' words':'';feedback();if(was){publish();$('steps').querySelectorAll('button').forEach((b,i)=>{b.disabled=i>s.done.length;});}});wrap.append(label,input,el('small',f.help||''),count);if(roleMapHas(f.id)){const row=el('div',undefined,'draft-tools'),button=el('button','Transmitir a '+OperationsAIContext.recipient(m,s,f.id));button.type='button';button.onclick=()=>openRadio(OperationsAIContext.recipient(m,s,f.id),s.answers[t.id]?.[f.id]||'');row.append(button);wrap.append(row);}return wrap;}));
$('finish').replaceChildren(el('h2','Mission record ready'),el('p','All eight workflow phases are recorded. Written work and AI exchanges remain available for instructor review. Completion is not an automated language or professional competence grade.'),el('p',m.id==='m4'?'D3 remains open. Completion of this learning workflow does not mean vessel clearance.':''));const download=el('button','Download complete evidence packet','primary');download.onclick=()=>exportRecord();$('finish').append(download);const readable=el('button','Download readable report');readable.onclick=()=>exportRecord('md');$('finish').append(readable);const review=el('details');review.append(el('summary','Review all recorded communications'));m.stages.forEach(st=>{review.append(el('h3',st.title));st.fields.forEach(f=>{review.append(el('strong',f.label),el('p',s.answers[st.id]?.[f.id]||'[Not submitted]'));});});$('finish').append(review);feedback();chat();}
function roleMapHas(id){return ['readback-message','relay-message','permit-order','deck-order','document-request','followup','briefing','traffic-message','clarification','location-message','cargo-query','lashing-order','challenge','master-brief'].includes(id);}
function updateContact(){activeContact=$('ai-contact').value;$('ai-role').textContent=activeContact;$('ai-context-note').textContent='Canal de '+activeContact+' · '+m.stages[s.stage].time;chat();}
function openRadio(contact,message=''){if(contact!==activeContact){run++;busy=false;$('ai-send').disabled=false;}const contacts=OperationsAIContext.contacts(m,s);$('ai-contact').replaceChildren(...contacts.map(x=>new Option(x,x)));$('ai-contact').value=contacts.includes(contact)?contact:contacts[0];updateContact();$('ai-input').value=message;$('ai-status').textContent='';$('ai-dialog').showModal();}
$('ai-contact').onchange=()=>{run++;busy=false;$('ai-send').disabled=false;updateContact();};
$('menu-radio').onclick=()=>openRadio(OperationsAIContext.contacts(m,s)[0]);
$('menu-situation').onclick=()=>$('workspace').scrollIntoView({behavior:'smooth'});
$('menu-docs').onclick=()=>document.querySelector('.source-section').scrollIntoView({behavior:'smooth'});
$('menu-record').onclick=()=>{document.querySelector('.trail').open=true;document.querySelector('.trail').scrollIntoView({behavior:'smooth'});};
function describeError(id){const t=m.stages[s.stage],f=t.fields.find(x=>x.id===id),v=String(s.answers[t.id]?.[id]||'').trim(),label=OperationsGuide.fieldLabels[id]||f.label;if(!v)return label+': falta tu respuesta.';if(f.expected&&v!==f.expected)return label+': la opción elegida no coincide con la fuente. Vuelve a consultar el documento.';return label+': desarrolla los detalles solicitados (mínimo '+f.min+' caracteres; tienes '+v.length+').';}
function tLabel(id){return m.stages[s.stage].fields.find(f=>f.id===id)?.label||id;}
function elError(link){const p=el('p');p.append(link);return p;}
$('submit').onclick=()=>{const result=C.commit(m,s);save();$('errors').replaceChildren(...result.errors.map(e=>el('p',e.message)));if(!result.ok){$('errors').replaceChildren(el('strong','Antes de entregar, revisa lo siguiente:'),...result.errors.map(e=>{const link=el('a',e.id.startsWith('doc-')?'Consulta el documento: '+m.documents.find(d=>'doc-'+d.id===e.id)?.title:describeError(e.id));link.href='#'+(e.id.startsWith('doc-')?e.id:'field-'+e.id);return elError(link);}));$('errors').focus();}else{publish();render();}};
$('continue').onclick=()=>{if(!s.done.includes(m.stages[s.stage].id))return;s.stage++;save();render();$('workspace').scrollIntoView({behavior:'smooth'});};
$('download-top').onclick=()=>exportRecord();$('back').onclick=e=>{if(parent!==window){e.preventDefault();parent.postMessage({type:'maresp-close-mission'},location.origin);}};
$('restart').onclick=()=>$('restart-dialog').showModal();$('cancel-restart').onclick=()=>$('restart-dialog').close();$('confirm-restart').onclick=()=>{try{localStorage.setItem(key+'_archive_'+Date.now(),JSON.stringify(s));}catch(e){$('save-status').textContent='Archive unavailable. Export before starting again.';$('restart-dialog').close();return;}s=C.fresh(m.id);save();publish();$('restart-dialog').close();render();};
$('ai-form').onsubmit=async e=>{e.preventDefault();if(busy)return;const text=$('ai-input').value.trim();if(!text){$('ai-status').textContent='Escribe el mensaje que quieres transmitir.';return;}const t=m.stages[s.stage],contact=activeContact,token=run;busy=true;$('ai-send').disabled=true;const outgoing={stage:t.id,contact,mode:'simulation',role:'user',content:text,time:new Date().toISOString()};s.messages.push(outgoing);save();chat();
try{const conversation=s.messages.filter(x=>x.stage===t.id&&x.mode==='simulation'&&x.contact===contact).slice(-12).map(x=>({role:x.role,content:x.content}));const result=await MaritimeAI.reply({dialogueMode:'simulation',system:OperationsAIContext.build(m,s,contact),messages:conversation,onStatus:x=>{if(run===token)$('ai-status').textContent=/busy/i.test(String(x))?'Canal ocupado; reintentando una vez…':'Esperando respuesta de '+contact+'…';}});if(run!==token)return;const problem=OperationsAIContext.audit(result.text);if(problem)throw Error(problem);s.messages.push({stage:t.id,contact,mode:'simulation',role:'assistant',content:result.text,model:result.model,time:new Date().toISOString()});s.log.push({stage:t.id,time:new Date().toISOString(),recipient:contact,text:'Intercambio operativo con '+contact+' registrado.'});save();publish();chat();feedback();if($('ai-input').value===text)$('ai-input').value='';$('ai-status').textContent='Respuesta de '+contact+' recibida. Intercambio registrado.';}catch(error){if(run===token)$('ai-status').textContent='Sin respuesta del interlocutor. '+error.message+' El mensaje se conserva para reintentar.';}finally{if(run===token){busy=false;$('ai-send').disabled=false;}}};

render();
})();
